### ISSUE TITLE
hd parameter not working for APOD

### ISSUE THREAD

**Issue by dinizthiagobr** [nasa/api-docs#65] opened 2016-01-07 18:19 UTC
The 'hd' parameter on APOD's API is not being accepted, it returns:

```
{
  "msg": "Bad Request incorrect field passed. Allowed request fields for apod method are 'concept_tags', 'date'",
  "service_version": "v1"
}
```

But on your website it is still listed as a valid parameter.

**Comment by brianthomas** [comment] 2016-01-07 18:32
I don't thing "HD" is an allowed parameter. My reading of the source shows that neither the code nor the docs (README) show that parameter as allowed.

**Comment by jovrtn** [comment] 2016-01-07 18:36
The 'hd' parameter was working in the previous version of the API, and is still listed on the APOD documentation: https://api.nasa.gov/api.html#apod

**Comment by brianthomas** [comment] 2016-01-07 18:45
Interesting. I just grepped the repo for the code and couldn't find it. Perhaps there is some kind of service interceptor at work here or perhaps it passes that parameter through to the underlying service somehow? I can't find anywhere in the codebase where it actually grabs from a different base url. @danhammer  will have to answer this one.

**Comment by jovrtn** [comment] 2016-01-07 18:50
The return value was `hdurl` if that helps, but it was definitely work just yesterday before the "service_version": "v1" update.

The return values from yesterday's picture for reference:

```json
{
  "url": "http://apod.nasa.gov/apod/image/1601/CatalinaBorrellyArcturus2016-01-01_Hemmerich600w.jpg",
  "media_type": "image",
  "explanation": "This timely, telescopic, two panel mosaic spans about 10 full moons across planet Earth's predawn skies. Recorded as the year began from Tenerife, Canary Islands, near the top of the frame are the faint coma and tail of Comet Borrelly (P/19). A comet with a seven year orbital period, Borrelly's nucleus was visited by the ion propelled spacecraft Deep Space 1 near the beginning of the 21st century. Anchoring the scene at the bottom is brilliant star Arcturus (Alpha Bootes) and Comet Catalina (C/2013 US10) a first time visitor from the Oort Cloud. Catalina's yellowish dust tail extends below and right. Buffeted by winds and storms from the Sun, the comet's complex ion tail sweeps up and toward the right, across most of the field of view. Remarkably, one of the composition's 30 second exposure subframes also caught the trail of a bright meteor, slashing toward the left between comets and bright star.",
  "title": "Comets and Bright Star",
  "hdurl": "http://apod.nasa.gov/apod/image/1601/CatalinaBorrellyArcturus2016-01-01_Hemmerich.jpg",
  "concepts": [
    "Comet",
    "Asteroid",
    "Sun",
    "Jupiter",
    "Planet",
    "Solar System",
    "Moon",
    "Earth"
  ]
}
```

[Also note that `media_type` seems to be gone from the new version, too.]

**Comment by brianthomas** [comment] 2016-01-07 18:51
I have a partial answer now. Looking at the apod code, its passing the high resolution image along by default. Make a call to the service for today, and you will see that the returned image url is the high resolution one.

**Comment by brianthomas** [comment] 2016-01-07 18:53
When I transferred the code over, I put in parameter validation. I believe (and Dan can correct me) that the prior service didnt validate the input query parameters, and 'hd' was simply passed through. It doesn't appear to have any effect (in the old code); you always got the high resolution image.

**Comment by jovrtn** [comment] 2016-01-07 18:54
@brianthomas Thanks for looking into it, however just checking against the APOD webpage, today's returned image is definitely the low res one:

API-returned image:
http://apod.nasa.gov/apod/image/1601/PIA20061NuSTARAndromeda600h.jpg

High res image from clicking on the picture on the webpage: http://apod.nasa.gov/apod/image/1601/PIA20061NuSTARAndromeda.jpg

**Comment by dinizthiagobr** [comment] 2016-01-07 18:55
Can't agree with you, @brianthomas , there was a difference. And by calling the service today you get the low resolution image.

**Comment by jovrtn** [comment] 2016-01-07 18:56
@brianthomas I haven't observed that to be the case using the API up until now—there was usually a difference between the url and hdurl values.

**Comment by dinizthiagobr** [comment] 2016-01-07 18:56
And as @jovrtn said, you used to get the high resolution image in 'hdurl' return parameter if using 'hd=True' during the call.

**Comment by brianthomas** [comment] 2016-01-07 18:57
Well, perhaps Dan was deploying from a different repo; I can only go with the code I see. Media_type is not present, neither is hdurl (I'd show you all the 'evidence' but the repo is private, unfortunately)

**Comment by dinizthiagobr** [comment] 2016-01-07 18:58
So that must be it. Media_type and hdurl was present for sure.

**Comment by dinizthiagobr** [comment] 2016-01-07 18:59
https://github.com/nasa/api-docs/issues/36

Check this issue opened a while ago, might be helpful for you guys to figure it out.

**Comment by brianthomas** [comment] 2016-01-07 19:09
Well, unless I can nail down the exact code which was deployed, the best I can do is to try to restore the functionality in the current service. Does media_type ever return any other value than "image"? The HD parameter should be straightforward to implement, but I wonder if is simply would be better to always supply the 'url' and 'hdurl' values instead (its not exactly a lot of extra bytes). 

I am unaware of other issues (yet)

**Comment by dinizthiagobr** [comment] 2016-01-07 19:11
Suplying both 'url' and 'hdurl' seems good. 
'Media_type' returns "image" or "video" in my limited experience with the API.

**Comment by jovrtn** [comment] 2016-01-07 19:13
In the case of the "video" media type, `url` was populated with the video embed link (e.g. https://www.youtube.com/embed/zR3Igc3Rhfg?rel=0) and `hdurl` wasn't returned at all.

**Comment by brianthomas** [comment] 2016-01-07 19:20
@jovrtn can you provide me with an apod date where there was video on that day?

**Comment by jovrtn** [comment] 2016-01-07 19:22
2015-12-28 was the most recent I believe.

**Comment by jovrtn** [comment] 2016-01-07 19:25
Out of curiosity, I queried the current version of the API for that date and it returns:

```json
{
  "error": "No APOD imagery for the given date.",
  "message": "Your request could not be processed.",
  "service_version": "v1"
}
```

Technically it's correct that there was no *picture* posted that day, but there was still content posted to APOD.

**Comment by brianthomas** [comment] 2016-01-07 19:29
Yeah, thats an issue with the date time zone of the deployed service. I believe that since the deployed service is in a different timezone now (GMT vs EDT where the APOD is, I think) it can fail for certain times of the day. I thought we had addressed this in prerelease testing, but looks like the issue is back. @jovrtn can you open a separate issue for that please?

**Comment by jovrtn** [comment] 2016-01-07 19:46
Happy to open an issue for the timezone thing if that's also occurring, however it appears that that all dates with videos are consistently returning "No APOD imagery for the given date" so I'm not sure if the issues are related.

For reference, these are the full API results from the 3 most recent video posts:

**2015-12-28**
```json
{
  "url": "https://www.youtube.com/embed/ZCBE8ocOkAQ?rel=0",
  "media_type": "video",
  "explanation": "The booster has landed. Spaceflight took a step toward the less expensive last week when the first stage of a Falcon 9 rocket set down on a landing pad not far from its Florida launch.  Previously, most rocket stages remained unrecovered -- with the significant exception of the Space Shuttles landing on a runway and their solid rocket boosters being fished back from the sea.  The landing occurred while the Falcon 9 second stage continued up to launch several communications satellites into low Earth orbit. The controlled landing, produced by SpaceX, was the first of its kind, but followed a booster landing last month by Blue Origin that did not involve launching satellites. Boeing and SpaceX were selected last year by NASA to launch future astronauts to the International Space Station. The pictured rocket booster will be analyzed for wear and reusability, but then is scheduled to be retired.   Follow APOD on: Facebook,  Google Plus, or Twitter",
  "title": "Falcon 9 First Stage Landing",
  "concepts": [
    "Spacecraft propulsion",
    "International Space Station",
    "Satellite",
    "Rocket",
    "Space Shuttle",
    "NASA",
    "Space exploration",
    "Konstantin Tsiolkovsky"
  ]
}
```

**2015-12-25**
```json
{
  "url": "https://www.youtube.com/embed/zR3Igc3Rhfg?rel=0",
  "media_type": "video",
  "explanation": "Want to build a scale model Solar System? A blue marble 1.4 centimeters (about half an inch) across would be a good choice for a scale model Earth. Since the Sun is 109 times the diameter of Earth, a 1.5 meter diameter balloon could represent the Sun. But the distance between the Earth and Sun, 150 million kilometers, would translate to just under 180 meters (590 feet) at the same scale. That would mean the completed project, including the orbits of the outer planets, is probably not going to fit in your backyard. Still, you might find enough room on a dry lakebed. Check out this video for an inspirational road trip through the Solar System to scale.",
  "title": "To Scale: The Solar System",
  "concepts": [
    "Earth",
    "Planet",
    "Sun",
    "Solar System",
    "Milky Way",
    "Moon",
    "Jupiter",
    "Mercury"
  ]
}
```

**2015-12-22**
```json
{
  "url": "http://player.vimeo.com/video/32095756?title=0&byline=0&portrait=0",
  "media_type": "video",
  "explanation": "Can you find which day is the winter solstice?  Each panel shows one day. With 360 movie panels, the sky over (almost) an entire year is shown in time lapse format as recorded by a video camera on the roof of the Exploratorium museum in San Francisco, California. The camera recorded an image every 10 seconds from before sunrise to after sunset and from mid-2009 to mid-2010.  A time stamp showing the local time of day is provided on the lower right. The videos are arranged chronologically, with July 28 shown on the upper left, and January 1 located about half way down.  In the videos, darkness indicates night, blue depicts clear day, while gray portrays pervasive daytime cloud cover. Many videos show complex patterns of clouds moving across the camera's wide field as that day progresses. The initial darkness in the middle depicts the delayed dawn and fewer daylight hours of winter. Although every day lasts 24 hours, nighttime lasts longest in the northern hemisphere in December and the surrounding winter months. Therefore, finding the panel with the longest night will locate the day of winter solstice -- which happens to be today in the northern hemisphere.  As the videos collectively end, sunset and then darkness descend first on the winter days just above the middle, and last on the mid-summer near the bottom.",
  "title": "Solstice Illuminated: A Year of Sky",
  "concepts": [
    "Winter solstice",
    "Solstice",
    "Northern Hemisphere",
    "Day",
    "Sunrise",
    "Equator",
    "Southern Hemisphere",
    "The Panel"
  ]
}
```

As I mentioned, for videos the url is just the video embed link instead of the image url.

**Comment by brianthomas** [comment] 2016-01-07 19:55
Ok, I've made a change to add back in "hdurl" in the response. The "HD" parameter should also be allowed now, but its ignored. You always get back url and hdurl fields in the response now. Let me know if its working right for you all.

**Comment by jovrtn** [comment] 2016-01-07 20:08
Looks good here; working for both today's date and previous entries using the date parameter. Thanks!

**Comment by brianthomas** [comment] 2016-01-07 20:15
OK, I just hacked in the missing 'media_type' parameter and handling of video content. Please take a look and let me know of any issues; one (minor, I think) difference, is that the current service incarnation will return "hdurl = null when the content is video. Is this acceptable?

**Comment by brianthomas** [comment] 2016-01-07 20:23
@jovrtn I now grok what you were trying to tell me about the video, I don't think there is a need (unless I am still missunderstanding) to open a new issue.

**Comment by jovrtn** [comment] 2016-01-07 20:25
It's a minor point, but there's a semantic difference between them where returning a null value might mean that it's possible for a video to have a high res version but that it's just not available for the current resource, but omitting it entirely leaves no doubt that an hdurl is not part of the presentation for video resources.

I would vote to not return it if possible, however in the short term I think people (myself included) can just check for null values in our app logic so not really a critical issue.

Thanks again for looking into these issues!

**Comment by brianthomas** [comment] 2016-01-07 20:30
OK @jovrtn  I hear you. I've redeployed a version of the service where hdurl will be omitted when its not present in the original page.

**Comment by dinizthiagobr** [comment] 2016-01-07 20:42
Everything working here @brianthomas , thank you for the fast response.
Feel free to close this issue if everything's set and done.

**Closed** 2016-01-07 22:12 UTC
